// src/components/forms/SubmitButton.vue
<template>
  <input type="submit" :value="props.text" />
</template>

<script setup lang="ts">
const props = defineProps({
  text: { type: String, required: false, default: "Valider" },
});
</script>

<style lang="scss" scoped>
input {
  border: none;
  color: $c-on-primary;
  background-color: $c-primary;
  border-radius: $form-input-radius;
  padding: 20px 25px;
  text-transform: uppercase;

  cursor: pointer;

  &:focus {
    outline: none;
    text-decoration: underline;
  }
}
</style>

// src/lib/components/design_system/form/SubmitButton.svelte
<script setup lang="ts">
	export let text: string = 'Valider';
</script>

<input type="submit" value={text} />

<style lang="scss">
	input {
		width: 100%;
		border: none;
		color: var(--c-on-primary);
		background-color: var(--c-primary);
		border-radius: var(--form-input-radius);
		padding: 20px 25px;
		text-transform: uppercase;

		cursor: pointer;

		&:focus {
			outline: none;
			text-decoration: underline;
		}
	}
</style>
